/**
 * Assemble chat system-prompt parts for /api/chat.
 * Pure string assembly — no I/O.
 */

import {
  CHAT_OUTPUT_CAPABILITIES_PROMPT,
  DEFAULT_SYSTEM_PROMPT,
  activeIntegrationsPrompt,
  conversationIsolationPrompt,
  cursorWebChatPrompt,
  isCursorStyleModel,
} from '@/lib/models/specs';
import { timeContextSystemPrompt } from '@/lib/chat/context/time-context';
import { REVIEWER_SYSTEM_PROMPT } from '@/lib/tools/review/claim-reviewer';
import type { ChatSkillInput } from '@/lib/chat/server/request';
import { formatMemoriesForSystemPrompt } from '@/lib/memories/prompt';
import { skillPersistenceGatePrompt } from '@/lib/skills/creator';
import { domainPolicyPrompt } from '@/lib/chat/server/domain-policy';
import {
  autoReviewStatusPrompt,
  memoryBehaviorPrompt,
  productUsageGuideDetailPrompt,
  productUsageGuidePrompt,
} from '@/lib/chat/server/product-guide';

export type BuildChatSystemPartsOpts = {
  model: string;
  systemPrompt: string;
  threadId: string;
  searchEnabled: boolean;
  authorizedIntegrations: string[];
  googleRequestedButUnauthorized: boolean;
  notionRequestedButUnauthorized?: boolean;
  githubRequestedButUnauthorized?: boolean;
  toolsGuidance: string;
  skills: ChatSkillInput[];
  memories?: Array<{ kind?: string; content?: string }>;
  requestReview: boolean;
  autoReview: boolean;
  referenceText: string;
  hasGeneratedImages: boolean;
  hasGeneratedFiles: boolean;
  /** Whether builtin Skill Creator is active (gates save_skill). */
  skillCreatorOn?: boolean;
  /** When Skill Creator is on — id/title list so save_skill can replace. */
  accountSkillCatalog?: string;
  /** Inject the longer product guide (user asked how to use / what commands). */
  expandProductGuide?: boolean;
  /** Latest user text used for domain/risk policy selection. */
  userAsk?: string;
};

export function buildChatSystemParts(opts: BuildChatSystemPartsOpts): string[] {
  const skillCreatorOn = Boolean(opts.skillCreatorOn);
  const systemParts: string[] = [];
  if (isCursorStyleModel(opts.model)) {
    systemParts.push(cursorWebChatPrompt({ searchEnabled: opts.searchEnabled }));
  }
  systemParts.push(timeContextSystemPrompt());
  systemParts.push(String(opts.systemPrompt || '').trim() || DEFAULT_SYSTEM_PROMPT);
  systemParts.push(CHAT_OUTPUT_CAPABILITIES_PROMPT);
  systemParts.push(productUsageGuidePrompt());
  if (opts.expandProductGuide) {
    systemParts.push(productUsageGuideDetailPrompt());
  }
  systemParts.push(skillPersistenceGatePrompt(skillCreatorOn));
  systemParts.push(memoryBehaviorPrompt());
  const domainPolicy = domainPolicyPrompt(opts.userAsk || '');
  if (domainPolicy) systemParts.push(domainPolicy);
  systemParts.push(
    autoReviewStatusPrompt({
      autoReview: Boolean(opts.autoReview),
      requestReview: Boolean(opts.requestReview),
    }),
  );
  if (opts.threadId) {
    systemParts.push(conversationIsolationPrompt(opts.threadId));
  }
  systemParts.push(
    activeIntegrationsPrompt({
      searchEnabled: opts.searchEnabled,
      integrations: opts.authorizedIntegrations,
      googleRequestedButUnauthorized: opts.googleRequestedButUnauthorized,
      notionRequestedButUnauthorized: opts.notionRequestedButUnauthorized,
      githubRequestedButUnauthorized: opts.githubRequestedButUnauthorized,
      skillCreatorOn,
    }),
  );
  if (opts.toolsGuidance) {
    systemParts.push(opts.toolsGuidance);
  }
  for (const skill of opts.skills) {
    const title = String(skill?.title || 'Skill').trim();
    const content = String(skill?.content || '').trim();
    if (!content) continue;
    systemParts.push(`Active Skill — ${title}:\n${content}`);
  }
  if (String(opts.accountSkillCatalog || '').trim()) {
    systemParts.push(String(opts.accountSkillCatalog).trim());
  }
  const memoryBlock = formatMemoriesForSystemPrompt(
    (opts.memories || [])
      .map((m) => ({
        kind: String(m?.kind || '').trim(),
        content: String(m?.content || '').trim(),
      }))
      .filter((m) => m.content),
  );
  if (memoryBlock) systemParts.push(memoryBlock);
  if (opts.requestReview) {
    systemParts.push(
      'The user explicitly requested a claim review of the conversation. Verify each assistant turn against that turn’s own tool receipts (not a pooled bag of all tools). If a claim lacks a real tool receipt for its turn, retract it. Otherwise confirm briefly.',
    );
  }
  if (opts.autoReview || opts.requestReview) {
    systemParts.push(REVIEWER_SYSTEM_PROMPT);
  }
  if (String(opts.referenceText || '').trim()) {
    systemParts.push(
      `Reference material provided by the user. Treat it as authoritative context:\n\n${String(opts.referenceText).trim()}`,
    );
  }

  if (opts.hasGeneratedImages) {
    systemParts.push(
      [
        'This chat already contains image(s) generated by Christmas Chat’s /image pipeline.',
        'They are shown in the UI and may be attached to later user turns for vision models.',
        'Never claim those images failed to generate, and never blame missing folders/workspaces.',
        'If the user asks about “这张图/刚才的图/生成的图”, refer to the generated image in this chat — do not web-search for substitutes unless asked.',
      ].join(' '),
    );
  }
  if (opts.hasGeneratedFiles) {
    systemParts.push(
      [
        'This chat already contains downloadable file(s) (create_file / create_spreadsheet / book or paper download).',
        'They appear in the Output / Files UI and as 【历史文件引用】 markers with fileId in the conversation.',
        'When the user asks you to read, summarize, or quote those files, call file_read with that file_id — do not claim you cannot read them when a marker is present.',
        'To add more files, call create_file or create_spreadsheet again — do not pretend a file exists without a successful tool receipt (ok:true).',
      ].join(' '),
    );
  }

  return systemParts;
}

export function joinChatSystemParts(parts: string[]): string {
  return parts.join('\n\n---\n\n');
}
