/**
 * Assemble chat system-prompt parts for /api/chat.
 * Pure string assembly — no I/O.
 */

import {
  CHAT_OUTPUT_CAPABILITIES_PROMPT,
  CURSOR_WEB_CHAT_PROMPT,
  DEFAULT_SYSTEM_PROMPT,
  activeIntegrationsPrompt,
  conversationIsolationPrompt,
  isCursorStyleModel,
} from '@/lib/models/specs';
import { timeContextSystemPrompt } from '@/lib/chat/context/time-context';
import { REVIEWER_SYSTEM_PROMPT } from '@/lib/tools/review/claim-reviewer';
import type { ChatSkillInput } from '@/lib/chat/server/request';

export type BuildChatSystemPartsOpts = {
  model: string;
  systemPrompt: string;
  threadId: string;
  searchEnabled: boolean;
  authorizedIntegrations: string[];
  googleRequestedButUnauthorized: boolean;
  toolsGuidance: string;
  skills: ChatSkillInput[];
  requestReview: boolean;
  autoReview: boolean;
  referenceText: string;
  hasGeneratedImages: boolean;
  hasGeneratedFiles: boolean;
};

export function buildChatSystemParts(opts: BuildChatSystemPartsOpts): string[] {
  const systemParts: string[] = [];
  if (isCursorStyleModel(opts.model)) {
    systemParts.push(CURSOR_WEB_CHAT_PROMPT);
  }
  systemParts.push(timeContextSystemPrompt());
  systemParts.push(String(opts.systemPrompt || '').trim() || DEFAULT_SYSTEM_PROMPT);
  systemParts.push(CHAT_OUTPUT_CAPABILITIES_PROMPT);
  if (opts.threadId) {
    systemParts.push(conversationIsolationPrompt(opts.threadId));
  }
  systemParts.push(
    activeIntegrationsPrompt({
      searchEnabled: opts.searchEnabled,
      integrations: opts.authorizedIntegrations,
      googleRequestedButUnauthorized: opts.googleRequestedButUnauthorized,
    }),
  );
  if (opts.toolsGuidance) {
    systemParts.push(opts.toolsGuidance);
  }
  for (const skill of opts.skills) {
    const title = String(skill?.title || 'Skill').trim();
    const content = String(skill?.content || '').trim();
    if (!content) continue;
    systemParts.push(`Active Skill — ${title}:\n${content}`);
  }
  if (opts.requestReview) {
    systemParts.push(
      'The user explicitly requested a claim review of the conversation. Verify each assistant turn against that turn’s own tool receipts (not a pooled bag of all tools). If a claim lacks a real tool receipt for its turn, retract it. Otherwise confirm briefly.',
    );
  }
  if (opts.autoReview || opts.requestReview) {
    systemParts.push(REVIEWER_SYSTEM_PROMPT);
  }
  if (String(opts.referenceText || '').trim()) {
    systemParts.push(
      `Reference material provided by the user. Treat it as authoritative context:\n\n${String(opts.referenceText).trim()}`,
    );
  }

  if (opts.hasGeneratedImages) {
    systemParts.push(
      [
        'This chat already contains image(s) generated by Christmas Chat’s /image pipeline.',
        'They are shown in the UI and may be attached to later user turns for vision models.',
        'Never claim those images failed to generate, and never blame missing folders/workspaces.',
        'If the user asks about “这张图/刚才的图/生成的图”, refer to the generated image in this chat — do not web-search for substitutes unless asked.',
      ].join(' '),
    );
  }
  if (opts.hasGeneratedFiles) {
    systemParts.push(
      [
        'This chat already contains downloadable file(s) created via create_file.',
        'They appear in the Output panel. Refer to those existing files when the user asks about them.',
        'To add more files, call create_file again — do not pretend a file exists without a successful create_file receipt.',
      ].join(' '),
    );
  }

  return systemParts;
}

export function joinChatSystemParts(parts: string[]): string {
  return parts.join('\n\n---\n\n');
}
